%% init
close all
clc
clear variables

% Add paths to functions and data
addpath('data')
addpath('functions')
addpath('classificators')

%% 2 - Datasett
% Open files and extact data (ready to use with Classifcation Learner app)
[train_1, test_1, true_1] = data2Table('ds-1.txt');
[train_2, test_2, true_2] = data2Table('ds-2.txt');
[train_3, test_3, true_3] = data2Table('ds-3.txt');

%% 5 - Gjenommforing av oppgaven
% Run closest neighbor classifcator, get best property combination
[NN_1, prop_1, C_NN_1, T_1] = closestNeighbor(train_1, test_1, true_1);
[NN_2, prop_2, C_NN_2, T_2] = closestNeighbor(train_2, test_2, true_2);
[NN_3, prop_3, C_NN_3, T_3] = closestNeighbor(train_3, test_3, true_3);
err_NN_1 = T_1{1,1}; 
err_NN_2 = T_2{1,1}; 
err_NN_3 = T_3{1,1};    

% Run min error classificator
[minErr_1, err_minErr_1, C_minErr_1] = minErrorClassificator(...
    train_1, test_1, prop_1, true_1);
[minErr_2, err_minErr_2, C_minErr_2] = minErrorClassificator(...
    train_2, test_2, prop_2, true_2);
[minErr_3, err_minErr_3, C_minErr_3] = minErrorClassificator(...
    train_3, test_3, prop_3, true_3);

% Run least squares method classificator
[LS_1, err_LS_1, C_LS_1] = leastSquaresMethod(...
    train_1, test_1, prop_1, true_1);
[LS_2, err_LS_2, C_LS_2] = leastSquaresMethod(...
    train_2, test_2, prop_2, true_2);
[LS_3, err_LS_3, C_LS_3] = leastSquaresMethod(...
    train_3, test_3, prop_3, true_3);

% Confusion matrices gathered and plotted
C = [...
    C_NN_1 C_NN_2 C_NN_3; ...
    C_minErr_1 C_minErr_2 C_minErr_3; ...
    C_LS_1 C_LS_2 C_LS_3 ...
    ];
meta = {...
    'Closest Neighbor (data set 1)', '',    ...
    'Closest Neighbor (data set 2)', '',    ...
    'Closest Neighbor (data set 3)', '';    ...
    '', '', '', '', '', '';                 ...
    'Minimum Error (data set 1)', '',       ...
    'Minimum Error (data set 2)', '',       ...
    'Minimum Error (data set 3)', '';       ...
    '', '', '', '', '', '';                 ...
    'Least Squares (data set 1)', '',       ...
    'Least squares (data set 2)', '',       ...
    'Least Squares (data set 3)', '';       ...
    '', '', '', '', '', ''                  ...
    };
plotConfusion(C,meta);

% Compare error rates
ERR = [...
    err_NN_1        err_NN_2        err_NN_3;       ...
    err_minErr_1    err_minErr_2    err_minErr_3;   ...
    err_LS_1        err_LS_2        err_LS_3        ...
    ];
best_classificators = sortErrorRates(ERR,meta)