function [T]= sortErrorRates(errorRates, meta)
meta(:,2:2:end) = [];
meta(2:2:end,:) = [];
T = table(...
    errorRates(:,1), meta(:,1), ...
    errorRates(:,2), meta(:,2), ...
    errorRates(:,3), meta(:,3)  ...
    );

for i=1:3
    [~, order] = sort(errorRates(:,i));
    errorRates(:,i) = sort(errorRates(:,i));
    meta(:,i) = meta(order', i);
end

T(:,1:2:end) = num2cell(errorRates);
T(:,2:2:end) = meta;
T.Properties.VariableNames = {...
    'Data_set_1', 'Classificator_1', ...
    'Data_set_2', 'Classificator_2', ...
    'Data_set_3', 'Classificator_3'  ...
    };

end